"use client";

import { useState } from "react";
import * as LucideIcons from "lucide-react";
import toast from "react-hot-toast";
import { useTheme } from "@/components/providers/theme-provider";
import { useAuth } from "@/components/providers/auth-provider";
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from "@react-pdf/renderer";

interface EncryptionKey {
	id: string;
	name: string;
	algorithm: string;
	fingerprint: string;
	created: Date;
	isActive: boolean;
	publicKey: string;
	privateKey: string;
}

interface EncryptionKeysStepProps {
	onComplete: () => void;
	isLoading?: boolean;
}

const styles = StyleSheet.create({
  page: { padding: 30 },
  header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  warningBox: { backgroundColor: '#fff3f3', padding: 15, marginBottom: 20, borderRadius: 5, border: '1pt solid #dc3545' },
  warningText: { color: '#dc3545', fontSize: 11, textAlign: 'center', fontWeight: 'bold' },
  warningSubText: { color: '#dc3545', fontSize: 10, textAlign: 'center', marginTop: 5 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginTop: 15, marginBottom: 10 },
  text: { fontSize: 11, marginBottom: 5 },
  codeText: { fontFamily: 'Courier', fontSize: 10, marginBottom: 5 },
  publicKey: { fontFamily: 'Courier', fontSize: 8, marginTop: 5 },
  footer: { fontSize: 9, color: 'gray', textAlign: 'center', marginTop: 30, fontStyle: 'italic' }
});

const RecoveryKitPDF = ({ user, keys, backupCodes }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>PrivaMail Account Recovery Kit</Text>
      
      <View style={styles.warningBox}>
        <Text style={styles.warningText}>⚠ KEEP THIS DOCUMENT SAFE — DO NOT SHARE WITH ANYONE</Text>
        <Text style={styles.warningSubText}>Store in a secure location (safe, encrypted USB, password manager)</Text>
      </View>

      <Text style={styles.sectionTitle}>Account Information</Text>
      <Text style={styles.text}>Email: {user?.email}</Text>
      <Text style={styles.text}>Account ID: {user?.id}</Text>
      <Text style={styles.text}>Created: {new Date().toLocaleDateString()}</Text>

      <Text style={styles.sectionTitle}>Recovery Codes (One-Time Use)</Text>
      {backupCodes.map((code: string, i: number) => (
        <Text key={i} style={styles.codeText}>{i + 1}. {code}</Text>
      ))}

      <Text style={styles.sectionTitle}>Encryption Key Information</Text>
      <Text style={styles.codeText}>Key Algorithm: {keys[0]?.algorithm || 'RSA-4096'}</Text>
      <Text style={styles.codeText}>Fingerprint: {keys[0]?.fingerprint || 'N/A'}</Text>
      <Text style={styles.codeText}>Key ID: {keys[0]?.id || 'N/A'}</Text>

      <Text style={styles.sectionTitle}>Public Key</Text>
      <Text style={styles.publicKey}>{keys[0]?.publicKey || 'N/A'}</Text>

      <Text style={styles.footer}>Generated by PrivaMail • This document is your account lifeline</Text>
    </Page>
  </Document>
);

export function EncryptionKeysStep({
	onComplete,
	isLoading,
}: EncryptionKeysStepProps) {
	const { darkMode } = useTheme();
	const { user } = useAuth();
	const [generatingKeys, setGeneratingKeys] = useState(false);
	const [hasDownloaded, setHasDownloaded] = useState(false);
	const [confirmedDownload, setConfirmedDownload] = useState(false);
	const [showTechnicalDetails, setShowTechnicalDetails] = useState(false);

	const backupCodes = [
		"ABCD-EFGH-IJKL", "MNOP-QRST-UVWX", "1234-5678-9012", "3456-7890-1234",
		"WXYZ-ABCD-EFGH", "5678-9012-3456", "IJKL-MNOP-QRST", "7890-1234-5678",
	];

	const [keys, setKeys] = useState<EncryptionKey[]>([
		{
			id: "default",
			name: "Default Encryption Key",
			algorithm: "RSA-4096",
			fingerprint: "AB:CD:EF:12:34:56",
			created: new Date(),
			isActive: true,
			publicKey: "DEFAULT_PUBLIC_KEY_PLACEHOLDER",
			privateKey: "DEFAULT_PRIVATE_KEY_PLACEHOLDER",
		},
	]);
	const [showConfirmDialog, setShowConfirmDialog] = useState(false);
	const [pendingKeyAction, setPendingKeyAction] = useState<{
		type: "activate";
		keyId: string;
	} | null>(null);

	// Generate new keys
	const handleGenerateKeys = () => {
		setGeneratingKeys(true);

		setTimeout(() => {
			const newKey: EncryptionKey = {
				id: `key_${Date.now()}`,
				name: "New Encryption Key",
				algorithm: "RSA-4096",
				fingerprint: "XY:Z1:23:45:67:89",
				created: new Date(),
				isActive: false,
				publicKey: `-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA${Math.random().toString(36).substring(2, 15)}\n${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}\n-----END PUBLIC KEY-----`,
				privateKey: `-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC${Math.random().toString(36).substring(2, 15)}\n${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}\n-----END PRIVATE KEY-----`,
			};

			setKeys((prev) => [...prev, newKey]);
			setGeneratingKeys(false);

			toast.success("New encryption keys generated successfully!");
		}, 2000);
	};

	// Export key functionality
	const handleExportKey = (keyData: EncryptionKey, type = "both") => {
		try {
			let content = "";
			let filename = "";

			if (type === "public") {
				content = keyData.publicKey;
				filename = `${keyData.name.replace(/\\s+/g, "_")}_public_key.pem`;
			} else if (type === "private") {
				content = keyData.privateKey;
				filename = `${keyData.name.replace(/\\s+/g, "_")}_private_key.pem`;
			} else {
				content = `${keyData.publicKey}\n\n${keyData.privateKey}`;
				filename = `${keyData.name.replace(/\\s+/g, "_")}_keypair.pem`;
			}

			const blob = new Blob([content], { type: "text/plain" });
			const url = window.URL.createObjectURL(blob);
			const link = document.createElement("a");
			link.href = url;
			link.download = filename;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);
			window.URL.revokeObjectURL(url);

			toast.success(
				`${type === "both" ? "Keypair" : type + " key"} exported successfully!`
			);
		} catch (error) {
			console.error("Export key error:", error);
			toast.error("Failed to export key. Please try again.");
		}
	};

	// Set key as active
	const handleSetKeyActive = (keyId: string) => {
		const key = keys.find((k) => k.id === keyId);
		if (!key || key.isActive) return;

		setPendingKeyAction({ type: "activate", keyId });
		setShowConfirmDialog(true);
	};

	// Confirm key action
	const confirmKeyAction = () => {
		if (pendingKeyAction?.type === "activate") {
			setKeys((prev) =>
				prev.map((key) => ({
					...key,
					isActive: key.id === pendingKeyAction.keyId,
				}))
			);

			toast.success("Encryption key activated successfully!");
		}
		setShowConfirmDialog(false);
		setPendingKeyAction(null);
	};

	return (
		<div className="space-y-6">
			{/* Confirmation Dialog */}
			{showConfirmDialog && (
				<div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
					<div
						className={`max-w-md w-full mx-4 p-6 rounded-lg shadow-xl ${
							darkMode ? "bg-gray-800" : "bg-white"
						}`}
					>
						<div className="flex items-center mb-4">
							<LucideIcons.AlertTriangle className="h-6 w-6 text-amber-500 mr-3" />
							<h3
								className={`text-lg font-medium ${
									darkMode ? "text-white" : "text-gray-900"
								}`}
							>
								Confirm Key Activation
							</h3>
						</div>
						<p
							className={`text-sm mb-6 ${
								darkMode ? "text-gray-300" : "text-gray-600"
							}`}
						>
							Are you sure you want to activate this encryption key? This will
							deactivate your current key and may affect access to previously
							encrypted emails.
						</p>
						<div className="flex justify-end space-x-3">
							<button
								onClick={() => setShowConfirmDialog(false)}
								className={`px-4 py-2 text-sm font-medium rounded-md transition-colors duration-200 ${
									darkMode
										? "text-gray-300 bg-gray-700 hover:bg-gray-600"
										: "text-gray-700 bg-gray-100 hover:bg-gray-200"
								}`}
							>
								Cancel
							</button>
							<button
								onClick={confirmKeyAction}
								className="px-4 py-2 text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 transition-colors duration-200"
							>
								Activate Key
							</button>
						</div>
					</div>
				</div>
			)}

			<div
				className={`p-5 rounded-lg border ${
					darkMode
						? "bg-brand-900 bg-opacity-20 border-brand-800"
						: "bg-brand-50 border-brand-100"
				}`}
			>
				<div className="flex">
					<div className="flex-shrink-0">
						<LucideIcons.Key
							className={`h-5 w-5 ${
								darkMode ? "text-brand-400" : "text-brand-600"
							}`}
						/>
					</div>
					<div className="ml-3">
						<h3
							className={`text-sm font-medium ${
								darkMode ? "text-brand-200" : "text-brand-800"
							}`}
						>
							About Encryption Keys
						</h3>
						<p
							className={`mt-2 text-sm ${
								darkMode ? "text-brand-300" : "text-brand-700"
							}`}
						>
							Your encryption keys are used to secure your emails. We've
							generated a pair of keys for you automatically - a public key that
							others use to send you encrypted messages, and a private key that
							only you can use to decrypt them.
						</p>
					</div>
				</div>
			</div>

			{/* Recovery Kit Download */}
			<div className={`p-5 rounded-lg border ${darkMode ? "bg-amber-900/20 border-amber-800" : "bg-amber-50 border-amber-200"}`}>
				<h3 className={`font-medium mb-2 flex items-center ${darkMode ? "text-amber-200" : "text-amber-800"}`}>
					<LucideIcons.FileText className="h-5 w-5 mr-2" /> Download Recovery Kit
				</h3>
				<div className={`text-sm mb-4 ${darkMode ? "text-amber-300/80" : "text-amber-700"}`}>
					<p className="mb-2">🔑 Your Recovery Kit contains:</p>
					<ul className="list-disc pl-5 mb-2 space-y-1">
						<li>8 one-time recovery codes</li>
						<li>Your encryption key fingerprint</li>
						<li>Your public key</li>
					</ul>
					<p className="font-semibold mt-2">
						⚠️ Without this kit, if you forget your password and lose your 2FA device, your account and all encrypted emails will be permanently inaccessible.
					</p>
				</div>
				
				{typeof window !== 'undefined' && (
					<PDFDownloadLink
						document={<RecoveryKitPDF user={user} keys={keys} backupCodes={backupCodes} />}
						fileName="PrivaMail_Recovery_Kit.pdf"
						onClick={() => setHasDownloaded(true)}
						className="inline-flex items-center px-4 py-2 bg-amber-500 hover:bg-amber-600 text-white text-sm font-medium rounded-md transition-colors"
					>
						{({ loading }) => (
							<>
								<LucideIcons.Download className="h-4 w-4 mr-2" />
								{loading ? "Generating PDF..." : "Download Recovery Kit (PDF)"}
							</>
						)}
					</PDFDownloadLink>
				)}

				<div className="mt-4 flex items-start">
					<input
						type="checkbox"
						id="confirm-download"
						checked={confirmedDownload}
						onChange={(e) => setConfirmedDownload(e.target.checked)}
						disabled={!hasDownloaded}
						className={`mt-1 h-4 w-4 rounded border-gray-300 text-brand-600 focus:ring-brand-500 ${!hasDownloaded ? "opacity-50 cursor-not-allowed" : ""}`}
					/>
					<label htmlFor="confirm-download" className={`ml-2 text-sm ${darkMode ? "text-gray-300" : "text-gray-700"} ${!hasDownloaded ? "opacity-50" : ""}`}>
						{hasDownloaded
							? "I have downloaded and securely stored my recovery kit"
							: "Download the recovery kit above first"}
					</label>
				</div>
			</div>

			<div className="space-y-4">
				{keys.map((keyData) => (
					<div
						key={keyData.id}
						className={`border rounded-lg overflow-hidden transition-all duration-200 ${
							keyData.isActive
								? darkMode
									? "border-green-800 ring-1 ring-green-800"
									: "border-green-200 ring-1 ring-green-200"
								: darkMode
								? "border-gray-700"
								: "border-gray-200"
						}`}
					>
						<div
							className={`px-4 py-3 border-b ${
								keyData.isActive
									? darkMode
										? "bg-green-900/10 border-green-800"
										: "bg-green-50 border-green-200"
									: darkMode
									? "bg-gray-750 border-gray-700"
									: "bg-gray-50 border-gray-200"
							}`}
						>
							<div className="flex justify-between items-center">
								<h3
									className={`text-sm font-medium ${
										darkMode ? "text-white" : "text-gray-900"
									}`}
								>
									{keyData.name}
								</h3>
								<div className="flex items-center space-x-2">
									{/* !keyData.isActive && (
										<button
											onClick={() => handleSetKeyActive(keyData.id)}
											className={`text-xs px-2 py-1 rounded transition-colors ${
												darkMode
													? "text-gray-400 hover:text-white hover:bg-gray-600"
													: "text-gray-500 hover:text-gray-900 hover:bg-gray-200"
											}`}
										>
											Set Active
										</button>
									) */}
									<span
										className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
											keyData.isActive
												? darkMode
													? "bg-green-900 text-green-200"
													: "bg-green-100 text-green-800"
												: darkMode
												? "bg-gray-700 text-gray-300"
												: "bg-gray-100 text-gray-600"
										}`}
									>
										{keyData.isActive ? "Active" : "Inactive"}
									</span>
								</div>
							</div>
						</div>
						<div
							className={`px-4 py-4 ${darkMode ? "bg-gray-800" : "bg-white"}`}
						>
							<button
								type="button"
								onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
								className={`flex items-center text-sm font-medium ${
									darkMode ? "text-gray-400 hover:text-gray-300" : "text-gray-500 hover:text-gray-700"
								}`}
							>
								<LucideIcons.ChevronRight
									className={`h-4 w-4 mr-1 transition-transform duration-200 ${showTechnicalDetails ? "rotate-90" : ""}`}
								/>
								Advanced Details
							</button>
							{showTechnicalDetails && (
								<div className={`mt-2 p-3 rounded-lg text-sm ${darkMode ? "bg-gray-700/50" : "bg-gray-50"}`}>
									<div className="grid grid-cols-2 gap-4">
										<div>
											<p
												className={`text-xs ${
													darkMode ? "text-gray-400" : "text-gray-500"
												}`}
											>
												<span className="font-medium">Algorithm:</span>{" "}
												{keyData.algorithm}
											</p>
											<p
												className={`text-xs ${
													darkMode ? "text-gray-400" : "text-gray-500"
												}`}
											>
												<span className="font-medium">Created:</span>{" "}
												{keyData.created.toLocaleDateString()}
											</p>
										</div>
										<div>
											<p
												className={`text-xs ${
													darkMode ? "text-gray-400" : "text-gray-500"
												}`}
											>
												<span className="font-medium">Fingerprint:</span>{" "}
												<span className="font-mono">{keyData.fingerprint}</span>
											</p>
											<p
												className={`text-xs ${
													darkMode ? "text-gray-400" : "text-gray-500"
												}`}
											>
												<span className="font-medium">Expiration:</span> Never
											</p>
										</div>
									</div>
									<div className="mt-4 flex flex-wrap items-center gap-2">
										{/* Export Options */}
										<div className="relative group">
											<button
												type="button"
												className={`inline-flex items-center px-2.5 py-1.5 border shadow-sm text-xs font-medium rounded transition-colors duration-200 ${
													darkMode
														? "border-gray-600 text-gray-300 bg-gray-700 hover:bg-gray-600"
														: "border-gray-300 text-gray-700 bg-white hover:bg-gray-50"
												} focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500`}
											>
												<LucideIcons.Download className="mr-1 h-4 w-4" />
												Export
												<LucideIcons.ChevronDown className="ml-1 h-3 w-3" />
											</button>
											<div
												className={`absolute bottom-full left-0 mb-1 w-40 rounded-md shadow-lg ${
													darkMode ? "bg-gray-700" : "bg-white"
												} ring-1 ring-black ring-opacity-5 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-10`}
											>
												<div className="py-1">
													<button
														onClick={() => handleExportKey(keyData, "public")}
														className={`block w-full text-left px-4 py-2 text-xs ${
															darkMode
																? "text-gray-300 hover:bg-gray-600"
																: "text-gray-700 hover:bg-gray-100"
														}`}
													>
														Public Key
													</button>
													<button
														onClick={() => handleExportKey(keyData, "private")}
														className={`block w-full text-left px-4 py-2 text-xs ${
															darkMode
																? "text-gray-300 hover:bg-gray-600"
																: "text-gray-700 hover:bg-gray-100"
														}`}
													>
														Private Key
													</button>
													<button
														onClick={() => handleExportKey(keyData, "both")}
														className={`block w-full text-left px-4 py-2 text-xs ${
															darkMode
																? "text-gray-300 hover:bg-gray-600"
																: "text-gray-700 hover:bg-gray-100"
														}`}
													>
														Both Keys
													</button>
												</div>
											</div>
										</div>
										<button
											type="button"
											onClick={handleGenerateKeys}
											disabled={generatingKeys}
											className={`inline-flex items-center px-3 py-2 border shadow-sm text-sm font-medium rounded-md transition-colors duration-200 ${
												darkMode
													? "border-gray-600 text-gray-300 bg-gray-700 hover:bg-gray-600"
													: "border-gray-300 text-gray-700 bg-white hover:bg-gray-50"
											} focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500 ${
												generatingKeys ? "opacity-70 cursor-not-allowed" : ""
											}`}
										>
											{generatingKeys ? (
												<>
													<svg
														className={`animate-spin -ml-1 mr-2 h-4 w-4 ${
															darkMode ? "text-gray-300" : "text-gray-700"
														}`}
														xmlns="http://www.w3.org/2000/svg"
														fill="none"
														viewBox="0 0 24 24"
													>
														<circle
															className="opacity-25"
															cx="12"
															cy="12"
															r="10"
															stroke="currentColor"
															strokeWidth="4"
														></circle>
														<path
															className="opacity-75"
															fill="currentColor"
															d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
														></path>
													</svg>
													Generating...
												</>
											) : (
												<>
													<LucideIcons.Plus className="mr-2 h-4 w-4" />
													Generate New Key
												</>
											)}
										</button>
									</div>
								</div>
							)}
						</div>
					</div>
				))}
			</div>

			<div
				className={`flex justify-end mt-6 pt-6 border-t ${
					darkMode ? "border-gray-700" : "border-gray-200"
				}`}
			>
				<button
					onClick={() => {
						if (!confirmedDownload) {
							toast.error("Please confirm that you have downloaded the recovery kit.");
							return;
						}
						onComplete();
					}}
					disabled={isLoading || !confirmedDownload}
					className={`inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white transition-colors duration-200 ${
						confirmedDownload 
							? "bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" 
							: "bg-gray-400 cursor-not-allowed"
					} ${
						isLoading ? "opacity-70 cursor-not-allowed" : ""
					}`}
				>
					{isLoading ? (
						<>
							<svg
								className="animate-spin -ml-1 mr-2 h-4 w-4 text-white"
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
							>
								<circle
									className="opacity-25"
									cx="12"
									cy="12"
									r="10"
									stroke="currentColor"
									strokeWidth="4"
								></circle>
								<path
									className="opacity-75"
									fill="currentColor"
									d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
								></path>
							</svg>
							Completing Setup...
						</>
					) : (
						<>
							Complete Setup
							<LucideIcons.Check className="ml-2 h-4 w-4" />
						</>
					)}
				</button>
			</div>
		</div>
	);
}
